### ISSUE TITLE
Dalli 2.6.0 requires mutable keys

### ISSUE THREAD

**Issue by bwillis** [n8/multi_fetch_fragments#6]
I was playing around and doing some performance measurements, but came across this error in my test app:

```
dalli (2.6.0) lib/active_support/cache/dalli_store.rb:270:in `force_encoding'
dalli (2.6.0) lib/active_support/cache/dalli_store.rb:270:in `expanded_key'
dalli (2.6.0) lib/active_support/cache/dalli_store.rb:128:in `block in read_multi'
dalli (2.6.0) lib/active_support/cache/dalli_store.rb:128:in `each'
dalli (2.6.0) lib/active_support/cache/dalli_store.rb:128:in `inject'
dalli (2.6.0) lib/active_support/cache/dalli_store.rb:128:in `read_multi'
multi_fetch_fragments (0.0.9) lib/multi_fetch_fragments.rb:32:in `render_collection_with_multi_fetch_cache'
```

It seems that the 2.6.0 bump brought in https://github.com/mperham/dalli/commit/aa7ff874dc3e522ad9255f363705a660d6727e7a which now requires that the given keys to cache.read_multi and cache.write must be mutable. I attempted to make a fix, and normally would have done a pull request, but after the fix the performance became worse: https://github.com/bwillis/multi_fetch_fragments/commit/02d86873fb50d9fc6901117a7430f7bad35cd336

Thoughts?

**Comment by bwillis** [comment]
Ok performance problems may have been a red herring, I'll post the pull request for review.
